version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: test-db-everyday_joke
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
  
  rabbitmq:
    image: rabbitmq:3.12-alpine
    container_name: test-rabbitmq-everyday_joke
    restart: "unless-stopped"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - ${RABBITMQ_PORT}:5672

  bot:
    container_name: test-bot-everyday_joke
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ./Makefile:/app/Makefile
      - ./.env:/app/.env.test
    depends_on:
      - db
      - rabbitmq
    command: ["make", "test-bot"]
  
