"""empty message

Revision ID: fd7f126acba7
Revises: 31a55a02a4c9
Create Date: 2023-06-28 12:07:51.934031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7f126acba7'
down_revision = '31a55a02a4c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscribed', sa.Boolean(), nullable=False))
    op.drop_column('user', 'subsribed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subsribed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'subscribed')
    # ### end Alembic commands ###
